version: '3.8'
services:
  neo4j:
    image: neo4j:5.15
    container_name: booknet-neo4j
    ports:
      - "7474:7474"  # Interface web
      - "7687:7687"  # Conexión desde Spring Boot
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
